chapter 1

== Develop a product or service
  I now believe that everyone should have at least one personal product for sale online.  It is best if this product is linked to something that you are passionate about.  If you have done your market research, this product or service fills a need or solves a problem. 
  There are probably several things that you feel passionate about or drawn to.  Look for where they intersect.  There is a product or service in that area.  Today, in 2015, you can get a lot of answers to your daily questions by just "Asking Google", We can take this a step farther to the websites that make the Internet the great collection of information that it is.  There is a growing layer of websites that aim to meet the needs of individuals asking questions on the internet and you can build a following that can produce passive income if you provide the answers that you have stumbled across in your life.
  
You also need to get an e-mail list.  This is a list of people who have given you permission to contact them about your content.  The best way to grow this list is to earn their interest into trusting you with their e-mail address.  Your goal is to get 1,000 true fans.  Today with a global internet connection, you should be able to get a few of the 7 Billion people on our planet that are interested in you content.  You can generate a good gross income with you 1,000 true fans.  If you only create $100 in products and services a year and those fans buy-in, you have just made $100,000 before paying for your costs!  Once you get your 1,000 true fans you can do marketing tests to see what else they would like you to help them with.
Make sure you make your content shareable.  Make it easy for people to pass along.  This will help you scale your list towards your goal of 1,000 true fans.
I also suggest that you keep your content available as long as possible.  Everyone is on their own journey.  I finaly decided to try this out at the end of 2015 after reading about these approaches for years.  Now you are reading this, and someone else will start their search later.  We need and are ready for the information at different times in our lives.
One reason that I decided that now was the time for me to get started was Mazacoin.  Mazacoin is digital Internet money based on Bitcoin.   It is very undervalued in mid 2015.  It has the power to free Native Americans (NDN, The Original Americans) from our modern slavery system that has been on them for years.  MazaCoin is decentralized and with it you can perform transactions with anyone on the planet in just a few minutes.  Everyone understands the idea of opening a lemonade stand.  Now imagine opening an Internet lemonade stand!  If your product or service is digital it can be immediately transfered to the buyer any time of the day.  If you have a physical product, you can still mail your item and it should be able to be anywhere in the world in a month or two.
