Chapter 2

== 1...2...3...?Profit 
Now that you have a product or service, How much do you need to charge for it? How much does it cost to repoduce it? An eBook is a great start.  It cost nothing to reproduce, so you can charge less for it and get more purchases.

You can look at this another way.  Holding on to a bit of undervalued Mazacoin could be very profitable.

There was a pizza sold for 10,000 Bitcoin very early in Bitcoin's history.  If you sold only part of that stash to pay for expenses and held on to the rest as profit, the Bitcoin would be worth thousands today at $350 a piece.  This was only from selling a single pizza.  What if you sold hundreds of them and saved only 1% of your profit in Mazacoin?

This is a good reason to sell items for mazacoin and keep a little for profit.  Another way to look at it.  I often say I wish everyone in China could send me a penny.  2 Billion times .01 equals 20 Million.  This could also be thought of as profit margin as well.  If you develop a product and you sell 2 Billion online at only a penny profit each, you have just made 20 Million.

